SET NAMES utf8mb4;

INSERT INTO quotes (qday, content) VALUES (1,  '지금 걷는 이 한 걸음이 당신을 바꿉니다.');
INSERT INTO quotes (qday, content) VALUES (2,  '내 몸은 나의 집, 매일 조금씩 돌보세요.');
INSERT INTO quotes (qday, content) VALUES (3,  '건강은 목표가 아닌, 습관입니다.');
INSERT INTO quotes (qday, content) VALUES (4,  '마음이 아플 땐, 천천히 숨을 쉬어보세요.');
INSERT INTO quotes (qday, content) VALUES (5,  '작은 실천 하나가 큰 변화를 만듭니다.');
INSERT INTO quotes (qday, content) VALUES (6,  '어제보다 한 걸음 더 나아간 당신, 멋져요.');
INSERT INTO quotes (qday, content) VALUES (7,  '몸이 보내는 신호에 귀 기울여 보세요.');
INSERT INTO quotes (qday, content) VALUES (8,  '하루 10분, 나를 위한 시간부터 시작해요.');
INSERT INTO quotes (qday, content) VALUES (9,  '당신의 건강은 당신이 가장 소중히 여겨야 할 자산입니다.');
INSERT INTO quotes (qday, content) VALUES (10, '기록하는 습관이 변화의 시작입니다.');
INSERT INTO quotes (qday, content) VALUES (11, '오늘의 선택이 내일의 건강을 만듭니다.');
INSERT INTO quotes (qday, content) VALUES (12, '천천히, 그러나 꾸준히.');
INSERT INTO quotes (qday, content) VALUES (13, '잘 먹고, 잘 자고, 잘 걷기.');
INSERT INTO quotes (qday, content) VALUES (14, '마음이 건강해야 몸도 웃어요.');
INSERT INTO quotes (qday, content) VALUES (15, '작은 승리 하나가 하루를 바꿉니다.');
INSERT INTO quotes (qday, content) VALUES (16, '운동은 몸에 주는 사랑의 표현입니다.');
INSERT INTO quotes (qday, content) VALUES (17, '쉬어도 괜찮아요. 포기만 하지 않으면.');
INSERT INTO quotes (qday, content) VALUES (18, '기록은 당신의 건강한 발자국입니다.');
INSERT INTO quotes (qday, content) VALUES (19, '지금 시작하는 당신이 가장 위대합니다.');
INSERT INTO quotes (qday, content) VALUES (20, '당신의 삶은 더 건강해질 자격이 있어요.');
INSERT INTO quotes (qday, content) VALUES (21, '운동은 당신을 위한 최고의 투자입니다.');
INSERT INTO quotes (qday, content) VALUES (22, '하루 1%의 변화, 1년 후 37배의 건강.');
INSERT INTO quotes (qday, content) VALUES (23, '당신은 당신의 리듬대로 살아도 돼요.');
INSERT INTO quotes (qday, content) VALUES (24, '몸과 마음이 모두 건강하길.');
INSERT INTO quotes (qday, content) VALUES (25, '자기 돌봄은 이기심이 아니라 생존입니다.');
INSERT INTO quotes (qday, content) VALUES (26, '건강한 나를 위해 오늘도 한 걸음.');
INSERT INTO quotes (qday, content) VALUES (27, '건강은 잃고 후회하기 전에 지켜야 합니다.');
INSERT INTO quotes (qday, content) VALUES (28, '운동은 나를 사랑하는 방식 중 하나예요.');
INSERT INTO quotes (qday, content) VALUES (29, '오늘도 잘 해냈어요, 정말.');
INSERT INTO quotes (qday, content) VALUES (30, '건강은 속도가 아니라 방향입니다.');
INSERT INTO quotes (qday, content) VALUES (31, '매일의 나를 응원해주는 앱, 그리고 당신.');